# Generated by Django 5.2.7 on 2026-01-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
