# Generated by Django 5.2.7 on 2026-01-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_note_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
